version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "web-app/yarn.lock" }}
            - node-modules-

      - run: yarn install

      - save_cache:
          key: node-modules-{{ checksum "web-app/yarn.lock" }}
          paths:
            - web-app/node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules/*


  deploy-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/packages/react-accessible-tooltip
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

  test-job:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn workspace react-accessible-tooltip test

  lint-job:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn workspace react-accessible-tooltip lint

  build-job:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn workspace react-accessible-tooltip build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job:
          filters:
            tags:
              only: /.*/
      - build-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - test-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - lint-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - deploy-job:
          requires:
            - lint-job
            - test-job
            - build-job
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
